apiVersion: v1
kind: ConfigMap
metadata:
  name: emailservice
data:
  PORT: "8080"
  DISABLE_PROFILER: "1"
  PYTHONUNBUFFERED: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: emailservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: email
          image: srikanthhg/emailservice:v1
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: emailservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: emailservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port